### ISSUE TITLE
Notes won't build

### ISSUE THREAD

**Issue by stelcodes** [zzamboni/enwrite#13]
Hugo v0.25, Enwrite v0.2.4, OS X  v10.12.6
Trying to build notes but keep getting this error message
![screen shot 2017-10-18 at 11 09 34 am](https://user-images.githubusercontent.com/22163194/31726803-e6aff752-b3f5-11e7-9d7c-9377908fda7e.png)
Any ideas? Btw, thanks for the all the work you put into this project. 🙂

**Comment by stelcodes** [comment]
I think I found the issue: https://github.com/gohugoio/hugo/blob/ff433f98133662063cbb16e220fd44c678c82823/docs/content/news/0-24.md
![screen shot 2017-10-18 at 11 23 04 am](https://user-images.githubusercontent.com/22163194/31727092-c294ab3c-b3f6-11e7-83a3-6cdc8971499d.png)

**Comment by stelcodes** [comment]
Corresponding enwrite code: https://github.com/zzamboni/enwrite/blob/03336b11c7296a5d94e19ab66760bef4571ae439/lib/output/hugo.rb#L151

Never worked with Ruby but I'm going to try to fix this.

**Comment by zzamboni** [comment]
Hi @stelabr - thanks for the report. It shouldn't be too hard to fix this, I'll give it a try when I have some time, but it may not be for a few days. If you can fix it and submit a PR, I'd be happy to review it.

**Comment by stelcodes** [comment]
Hey, thank you! I'm going to try my best, but I think it's a bit more complicated than I thought. Trying to get the clone to execute. Do I have to use Rake for that?

**Comment by zzamboni** [comment]
Normally just running `./bin/enwrite` from the checkout directory should work. What error are you getting?

**Comment by stelcodes** [comment]
At first, I was getting the same error messages even after removing the "-f" flag from the code, so I thought it must be running the enwrite in my $PATH that I installed via gem. So I uninstalled using gem and now I'm getting this.

![screen shot 2017-10-18 at 8 42 11 pm](https://user-images.githubusercontent.com/22163194/31748950-dd90e556-b444-11e7-97bb-485e3d929fc6.png)

So even though I ran the command `./bin/enwrite`, somehow it ran the code in my $PATH. Weird...

**Comment by ozgurOdun** [comment]
Hello, is there any update on this issue, 
im stuck at here too.

**Comment by zzamboni** [comment]
This issue has been fixed by #14 - thanks @ozgurOdun for the PR!

**Comment by jakeoung** [comment]
I still have the same error message although I download the recent repository.

**Comment by zzamboni** [comment]
@jakeoung can you post the exact error you are getting? Could it be that there is still an older copy of enwrite on your system (maybe installed via `gem`)?
